### ISSUE TITLE
interpolateMissing operation

### ISSUE THREAD

**Issue by abramvandergeest** [project-flogo/catalystml-flogo#108]
* __interpolateMissing__: Fill in missing values
    * Input
        * data - [array, map] data to be filled in
        * col - [int, string, array] the column(s) to be filled in
    * Params
        * how - [string] mean: substitutes mean of included values for Missing, linear: interpolates linearly from adjacent values
            * Optional - True
            * Default- "mean"
            * allowed: ["mean","linear"]
        * edges - [string] for linear how to handle edges
            * Optional - True
            * allowed: []
    * OutputType - [array, map]

**Comment by SteveNY-Tibco** [comment]
Implemented
