### ISSUE TITLE
date operation

### ISSUE THREAD

**Issue by abramvandergeest** [project-flogo/catalystml-flogo#110]
* __date__: (year,month,day, etc.) extract date information from string
    * Input
        * data - [string]
            * Optional=False
    * Params
        * format - [string]
            * Optional=True
            * Default=””  We will get the proper format
    * OutputType - [datetime object]  (datatime object includes properties, month etc.)

**Comment by abramvandergeest** [comment]
This has been put in the Utils Dir: PR https://github.com/project-flogo/catalystml-flogo/pull/138

**Comment by SteveNY-Tibco** [comment]
Dir issue has been solved: PR#140
