### ISSUE TITLE
reshape operation

### ISSUE THREAD

**Issue by abramvandergeest** [project-flogo/catalystml-flogo#21]
* __reShape__: change the dimensionality of a matrix without changing the underlying data
   * Input
        * data - [array] data to be reshaped
        * shape - [array]  array of integers where: 1) length of array  number of  output dimensions and 2) each integer specifies the number of values for a given dimension.  If the integer is 0 that dimension is sized to fit the data. i.e. [0,2,3] for a 24 value array means a 4x2x3 matrix
    * OutputType - [matrix]

**Comment by abramvandergeest** [comment]
I have change 0 to be -1 in the spec.

**Comment by abramvandergeest** [comment]
This needs to be moved from math to cleaning.  Looking closer at the code now.

**Comment by abramvandergeest** [comment]
@skothari-tibco I could be wrong but it looks like this is only for 2 dimensions correct?

**Comment by skothari-tibco** [comment]
Yes.

**Comment by abramvandergeest** [comment]
The primary use of this function is for image processing/TF which requires higher rank tensors.
(Primary use case is to make a rank 3 tensor and make a rank 4 tensor to include a given image into a "batch."

**Comment by abramvandergeest** [comment]
awaiting approval on PR https://github.com/project-flogo/catalystml-flogo/pull/141

**Comment by abramvandergeest** [comment]
Done
