### ISSUE TITLE
Standardized logging

### ISSUE THREAD

**Issue by abramvandergeest** [project-flogo/catalystml-flogo#55]
I propose that when we write an operation we include info level logging at the beginning and end that says something like "starting xyz operation" and "finishing xyz".  Then after each info log there is a debug level log that for the beginning includes the inputs and params and for the end includes outputs.  What does everyone think?  Any further suggestions?
@fm-tibco @SteveNY-Tibco @skothari-tibco

**Comment by skothari-tibco** [comment]
Sounds Good. 👍

**Comment by abramvandergeest** [comment]
I believe Samip is putting this in the engine/action documentation so I am marking this closed.
