### ISSUE TITLE
input / output not working properly

### ISSUE THREAD

**Issue by abramvandergeest** [project-flogo/catalystml-flogo#92]
During testing of the input/output of data into a structure I discovered that inputing an array with two values (an array and a string) and trying to name both:
  "input": [
    {
      "type": "array",
      "label": ["data","paragraph"]
    }
  ],
Did not work because $paragraph and $data were empty.
I was going to do further input/output testing, but it sorta required this input to work so will test more after this.

**Comment by skothari-tibco** [comment]
I believe this has been addressed.

**Comment by abramvandergeest** [comment]
Indeed
